# docker run --rm -it -v $(pwd)/:/usr/src/app -p 3000:3000 node:15 bash
# or
# docker build -t ajjordy/hello-express .
# docker run -p 3000:3000 ajjordy/hello-express 
FROM node:15

WORKDIR /usr/src/app
# COPY . .

EXPOSE 3000
# CMD [ "node", "index.js" ]